local myname, ns = ...
local L = LibStub("AceLocale-3.0"):GetLocale(myname, false)

local path_meta = {__index = {
    label = "Path to treasure",
    atlas = "map-icon-SuramarDoor.tga",
    path = true,
    scale = 1.1,
}}

ns.map_spellids = {
    -- [2352] = 0, -- Founder's Point
    -- [2351] = 0, -- Razorwind Shores
}

ns.points = {
   [2352] = { -- Founder's Point
        [52733871] = ({
            label = L["Secret Souvenir 1"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_01_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116392},
        }),
        [53234019] = ({
            label = L["Secret Souvenir 2"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_02_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116334},
        }),
        [53794169] = ({
            label = L["Secret Souvenir 3"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_03_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116335},
        }),
        [56004108] = ({
            label = L["Secret Souvenir 4"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_04_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116336},
        }),
        [57254528] = ({
            label = L["Secret Souvenir 5"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_05_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116337},
        }),
        [52073281] = ({
            label = L["Secret Souvenir 6"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_06_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116338},
        }),
        [57972688] = ({
            label = L["Secret Souvenir 7"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_07_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116339},
        }),
        [54482731] = ({
            label = L["Secret Souvenir 8"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_08_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116340},
        }),
        [49182706] = ({
            label = L["Secret Souvenir 9"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_09_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116341},
        }),
        [59284487] = ({
            label = L["Secret Souvenir 10"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_10_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116342},
        }),
        [64323651] = ({
            label = L["Secret Souvenir 11"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_11_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116343},
        }),
        [63614161] = ({
            label = L["Secret Souvenir 12"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_12_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116344},
        }),
        [64385112] = ({
            label = L["Secret Souvenir 13"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_13_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116345},
        }),
        [67315771] = ({
            label = L["Secret Souvenir 14"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_14_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116346},
        }),
        [59926245] = ({
            label = L["Secret Souvenir 15"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_15_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116347},
        }),
        [55925705] = ({
            label = L["Secret Souvenir 16"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_16_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116348},
        }),
        [58316518] = ({
            label = L["Secret Souvenir 17"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_17_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116349},
        }),
        [54156468] = ({
            label = L["Secret Souvenir 18"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_18_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116350},
        }),
        [47825541] = ({
            label = L["Secret Souvenir 19"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_19_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116351},
        }),
        [47276180] = ({
            label = L["Secret Souvenir 20"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_20_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116352},
        }),
        [46655890] = ({
            label = L["Secret Souvenir 21"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_21_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116353},
        }),
        [39525994] = ({
            label = L["Secret Souvenir 22"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_22_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116354},
        }),
        [38006400] = ({
            label = L["Secret Souvenir 23"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_23_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116355},
        }),
        [34687220] = ({
            label = L["Secret Souvenir 24"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_24_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116356},
        }),
        [37715712] = ({
            label = L["Secret Souvenir 25"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_25_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116357},
        }),
        [42104300] = ({
            label = L["Secret Souvenir 26"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_26_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116358},
        }),
        [44352946] = ({
            label = L["Secret Souvenir 27"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_27_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116359},
        }),
        [39193009] = ({
            label = L["Secret Souvenir 28"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_28_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116360},
        }),
        [40512554] = ({
            label = L["Secret Souvenir 29"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_29_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116361},
        }),
        [41992983] = ({
            label = L["Secret Souvenir 30"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_30_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116362},
        }),
        [32173871] = ({
            label = L["Secret Souvenir 31"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_31_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116363},
        }),
        [28304735] = ({
            label = L["Secret Souvenir 32"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_32_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116364},
        }),
        [37044528] = ({
            label = L["Secret Souvenir 33"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_33_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116365},
        }),
        [35674951] = ({
            label = L["Secret Souvenir 34"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_34_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116366},
        }),
        [34506057] = ({
            label = L["Secret Souvenir 35"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_35_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116367},
        }),
        [32827092] = ({
            label = L["Secret Souvenir 36"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_36_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116368},
        }),
        [45286427] = ({
            label = L["Secret Souvenir 37"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_37_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116369},
        }),
        [49187168] = ({
            label = L["Secret Souvenir 38"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_38_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116370},
        }),
        [55407499] = ({
            label = L["Secret Souvenir 39"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_39_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116371},
        }),
        [62078127] = ({
            label = L["Secret Souvenir 40"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_40_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116372},
        }),
        [75208348] = ({
            label = L["Secret Souvenir 41"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_41_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116373},
        }),
        [61366617] = ({
            label = L["Secret Souvenir 42"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_42_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116374},
        }),
        [59605064] = ({
            label = L["Secret Souvenir 43"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_43_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116375},
        }),
        [56702083] = ({
            label = L["Secret Souvenir 44"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_44_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116376},
        }),
        [44741721] = ({
            label = L["Secret Souvenir 45"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_45_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116377},
        }),
        [31650823] = ({
            label = L["Secret Souvenir 46"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_46_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116378},
        }),
        [07393764] = ({
            label = L["Secret Souvenir 47"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_47_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116379},
        }),
        [43385540] = ({
            label = L["Secret Souvenir 48"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_48_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116380},
        }),
        [72833522] = ({
            label = L["Secret Souvenir 49"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_49_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116381},
        }),
        [57103880] = ({
            label = L["Secret Souvenir 50"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_50_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116382},
        }),
        [55644968] = ({
            label = L["Secret Souvenir 51"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_51_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116393},
        }),
        [39093130] = ({
            label = L["Secret Souvenir 52"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_52_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116383},
        }),
        [53973336] = ({
            label = L["Secret Souvenir 53"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_53_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116384},
        }),
        [64955621] = ({
            label = L["Secret Souvenir 54"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_54_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116385},
        }),
        [48965727] = ({
            label = L["Secret Souvenir 54"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_54_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116385},
        }),	
        [60285262] = ({
            label = L["Secret Souvenir 54"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_54_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116385},
        }),				
        [36454734] = ({
            label = L["Secret Souvenir 55"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_55_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116386},
        }),
        [43516238] = ({
            label = L["Secret Souvenir 56"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_56_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116387},
        }),
        [62098214] = ({
            label = L["Secret Souvenir 57"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_57_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116388},
        }),
        [76905608] = ({
            label = L["Secret Souvenir 58"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_58_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116389},
        }),
        [19304260] = ({
            label = L["Secret Souvenir 59"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_59_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116390},
        }),
        [55238614] = ({
            label = L["Secret Souvenir 60"],
            cont = true,
            ZamestoTV_Remix = true,
            note = L["FP_60_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
            achievement = {id = 63605, criteria = 116391},
        }),
    },
    [2351] = { -- Razorwind Shores
        [54205690] = ({
            label = L["Souvenir Seeker 1"],
            cont = true,
            achievement = {id = 63441, criteria = 115868},
            ZamestoTV_Remix = true,
            note = L["RS_01_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [54805750] = ({
            label = L["Souvenir Seeker 2"],
            cont = true,
            achievement = {id = 63441, criteria = 115871},
            ZamestoTV_Remix = true,
            note = L["RS_02_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [53305660] = ({
            label = L["Souvenir Seeker 3"],
            cont = true,
            achievement = {id = 63441, criteria = 115872},
            ZamestoTV_Remix = true,
            note = L["RS_03_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [52705270] = ({
            label = L["Souvenir Seeker 4"],
            cont = true,
            achievement = {id = 63441, criteria = 115873},
            ZamestoTV_Remix = true,
            note = L["RS_04_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [53904890] = ({
            label = L["Souvenir Seeker 5"],
            cont = true,
            achievement = {id = 63441, criteria = 115874},
            ZamestoTV_Remix = true,
            note = L["RS_05_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [58504950] = ({
            label = L["Souvenir Seeker 6"],
            cont = true,
            achievement = {id = 63441, criteria = 115875},
            ZamestoTV_Remix = true,
            note = L["RS_06_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [51505870] = ({
            label = L["Souvenir Seeker 7"],
            cont = true,
            achievement = {id = 63441, criteria = 115876},
            ZamestoTV_Remix = true,
            note = L["RS_07_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [63574418] = ({
            label = L["Souvenir Seeker 8"],
            cont = true,
            achievement = {id = 63441, criteria = 115877},
            ZamestoTV_Remix = true,
            note = L["RS_08_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [62505210] = ({
            label = L["Souvenir Seeker 9"],
            cont = true,
            achievement = {id = 63441, criteria = 115878},
            ZamestoTV_Remix = true,
            note = L["RS_09_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [64405830] = ({
            label = L["Souvenir Seeker 10"],
            cont = true,
            achievement = {id = 63441, criteria = 115879},
            ZamestoTV_Remix = true,
            note = L["RS_10_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [69007600] = ({
            label = L["Souvenir Seeker 11"],
            cont = true,
            achievement = {id = 63441, criteria = 115880},
            ZamestoTV_Remix = true,
            note = L["RS_11_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [62209030] = ({
            label = L["Souvenir Seeker 12"],
            cont = true,
            achievement = {id = 63441, criteria = 115881},
            ZamestoTV_Remix = true,
            note = L["RS_12_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [61508980] = ({
            label = L["Souvenir Seeker 13"],
            cont = true,
            achievement = {id = 63441, criteria = 115882},
            ZamestoTV_Remix = true,
            note = L["RS_13_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [54408150] = ({
            label = L["Souvenir Seeker 14"],
            cont = true,
            achievement = {id = 63441, criteria = 115883},
            ZamestoTV_Remix = true,
            note = L["RS_14_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [52007240] = ({
            label = L["Souvenir Seeker 15"],
            cont = true,
            achievement = {id = 63441, criteria = 115884},
            ZamestoTV_Remix = true,
            note = L["RS_15_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [51106960] = ({
            label = L["Souvenir Seeker 16"],
            cont = true,
            achievement = {id = 63441, criteria = 115885},
            ZamestoTV_Remix = true,
            note = L["RS_16_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [52606430] = ({
            label = L["Souvenir Seeker 17"],
            cont = true,
            achievement = {id = 63441, criteria = 115886},
            ZamestoTV_Remix = true,
            note = L["RS_17_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [44605440] = ({
            label = L["Souvenir Seeker 18"],
            cont = true,
            achievement = {id = 63441, criteria = 115887},
            ZamestoTV_Remix = true,
            note = L["RS_18_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [43705060] = ({
            label = L["Souvenir Seeker 19"],
            cont = true,
            achievement = {id = 63441, criteria = 115888},
            ZamestoTV_Remix = true,
            note = L["RS_19_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [39305780] = ({
            label = L["Souvenir Seeker 20"],
            cont = true,
            achievement = {id = 63441, criteria = 115889},
            ZamestoTV_Remix = true,
            note = L["RS_20_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [41606690] = ({
            label = L["Souvenir Seeker 21"],
            cont = true,
            achievement = {id = 63441, criteria = 115890},
            ZamestoTV_Remix = true,
            note = L["RS_21_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [42707000] = ({
            label = L["Souvenir Seeker 22"],
            cont = true,
            achievement = {id = 63441, criteria = 115891},
            ZamestoTV_Remix = true,
            note = L["RS_22_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [44906610] = ({
            label = L["Souvenir Seeker 23"],
            cont = true,
            achievement = {id = 63441, criteria = 115892},
            ZamestoTV_Remix = true,
            note = L["RS_23_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [46707530] = ({
            label = L["Souvenir Seeker 24"],
            cont = true,
            achievement = {id = 63441, criteria = 115893},
            ZamestoTV_Remix = true,
            note = L["RS_24_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [40807870] = ({
            label = L["Souvenir Seeker 25"],
            cont = true,
            achievement = {id = 63441, criteria = 115894},
            ZamestoTV_Remix = true,
            note = L["RS_25_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [38708020] = ({
            label = L["Souvenir Seeker 26"],
            cont = true,
            achievement = {id = 63441, criteria = 115895},
            ZamestoTV_Remix = true,
            note = L["RS_26_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [44008740] = ({
            label = L["Souvenir Seeker 27"],
            cont = true,
            achievement = {id = 63441, criteria = 115896},
            ZamestoTV_Remix = true,
            note = L["RS_27_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [51108990] = ({
            label = L["Souvenir Seeker 28"],
            cont = true,
            achievement = {id = 63441, criteria = 115897},
            ZamestoTV_Remix = true,
            note = L["RS_28_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [64006950] = ({
            label = L["Souvenir Seeker 29"],
            cont = true,
            achievement = {id = 63441, criteria = 115898},
            ZamestoTV_Remix = true,
            note = L["RS_29_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [62006320] = ({
            label = L["Souvenir Seeker 30"],
            cont = true,
            achievement = {id = 63441, criteria = 115899},
            ZamestoTV_Remix = true,
            note = L["RS_30_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [59706470] = ({
            label = L["Souvenir Seeker 31"],
            cont = true,
            achievement = {id = 63441, criteria = 115900},
            ZamestoTV_Remix = true,
            note = L["RS_31_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [58006380] = ({
            label = L["Souvenir Seeker 32"],
            cont = true,
            achievement = {id = 63441, criteria = 115901},
            ZamestoTV_Remix = true,
            note = L["RS_32_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [57906970] = ({
            label = L["Souvenir Seeker 33"],
            cont = true,
            achievement = {id = 63441, criteria = 115902},
            ZamestoTV_Remix = true,
            note = L["RS_33_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [50506260] = ({
            label = L["Souvenir Seeker 34"],
            cont = true,
            achievement = {id = 63441, criteria = 115903},
            ZamestoTV_Remix = true,
            note = L["RS_34_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [51006510] = ({
            label = L["Souvenir Seeker 35"],
            cont = true,
            achievement = {id = 63441, criteria = 115904},
            ZamestoTV_Remix = true,
            note = L["RS_35_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [47606210] = ({
            label = L["Souvenir Seeker 36"],
            cont = true,
            achievement = {id = 63441, criteria = 115905},
            ZamestoTV_Remix = true,
            note = L["RS_36_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [48406170] = ({
            label = L["Souvenir Seeker 37"],
            cont = true,
            achievement = {id = 63441, criteria = 115906},
            ZamestoTV_Remix = true,
            note = L["RS_37_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [48205850] = ({
            label = L["Souvenir Seeker 38"],
            cont = true,
            achievement = {id = 63441, criteria = 115907},
            ZamestoTV_Remix = true,
            note = L["RS_38_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [48705410] = ({
            label = L["Souvenir Seeker 39"],
            cont = true,
            achievement = {id = 63441, criteria = 115908},
            ZamestoTV_Remix = true,
            note = L["RS_39_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [55905050] = ({
            label = L["Souvenir Seeker 40"],
            cont = true,
            achievement = {id = 63441, criteria = 115909},
            ZamestoTV_Remix = true,
            note = L["RS_40_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [56404840] = ({
            label = L["Souvenir Seeker 41"],
            cont = true,
            achievement = {id = 63441, criteria = 115910},
            ZamestoTV_Remix = true,
            note = L["RS_41_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [55506070] = ({
            label = L["Souvenir Seeker 42"],
            cont = true,
            achievement = {id = 63441, criteria = 115911},
            ZamestoTV_Remix = true,
            note = L["RS_42_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [57205810] = ({
            label = L["Souvenir Seeker 43"],
            cont = true,
            achievement = {id = 63441, criteria = 115912},
            ZamestoTV_Remix = true,
            note = L["RS_43_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [79914050] = ({
            label = L["Souvenir Seeker 44"],
            cont = true,
            achievement = {id = 63441, criteria = 115913},
            ZamestoTV_Remix = true,
            note = L["RS_44_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [41872446] = ({
            label = L["Souvenir Seeker 45"],
            cont = true,
            achievement = {id = 63441, criteria = 115914},
            ZamestoTV_Remix = true,
            note = L["RS_45_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [22904250] = ({
            label = L["Souvenir Seeker 46"],
            cont = true,
            achievement = {id = 63441, criteria = 115915},
            ZamestoTV_Remix = true,
            note = L["RS_46_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [75708880] = ({
            label = L["Souvenir Seeker 47"],
            cont = true,
            achievement = {id = 63441, criteria = 115916},
            ZamestoTV_Remix = true,
            note = L["RS_47_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [58805540] = ({
            label = L["Souvenir Seeker 48"],
            cont = true,
            achievement = {id = 63441, criteria = 115917},
            ZamestoTV_Remix = true,
            note = L["RS_48_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [51505400] = ({
            label = L["Souvenir Seeker 49"],
            cont = true,
            achievement = {id = 63441, criteria = 115918},
            ZamestoTV_Remix = true,
            note = L["RS_49_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [53605450] = ({
            label = L["Souvenir Seeker 50"],
            cont = true,
            achievement = {id = 63441, criteria = 115921},
            ZamestoTV_Remix = true,
            note = L["RS_50_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [59005600] = ({
            label = L["Souvenir Seeker 51"],
            cont = true,
            achievement = {id = 63441, criteria = 115922},
            ZamestoTV_Remix = true,
            note = L["RS_51_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [47205970] = ({
            label = L["Souvenir Seeker 52"],
            cont = true,
            achievement = {id = 63441, criteria = 115923},
            ZamestoTV_Remix = true,
            note = L["RS_52_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [63707140] = ({
            label = L["Souvenir Seeker 53"],
            cont = true,
            achievement = {id = 63441, criteria = 115924},
            ZamestoTV_Remix = true,
            note = L["RS_53_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [59905440] = ({
            label = L["Souvenir Seeker 54"],
            cont = true,
            achievement = {id = 63441, criteria = 115925},
            ZamestoTV_Remix = true,
            note = L["RS_54_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [52607310] = ({
            label = L["Souvenir Seeker 55"],
            cont = true,
            achievement = {id = 63441, criteria = 115926},
            ZamestoTV_Remix = true,
            note = L["RS_55_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [55206180] = ({
            label = L["Souvenir Seeker 56"],
            cont = true,
            achievement = {id = 63441, criteria = 115927},
            ZamestoTV_Remix = true,
            note = L["RS_56_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [39107380] = ({
            label = L["Souvenir Seeker 57"],
            cont = true,
            achievement = {id = 63441, criteria = 115928},
            ZamestoTV_Remix = true,
            note = L["RS_57_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [75304840] = ({
            label = L["Souvenir Seeker 58"],
            cont = true,
            achievement = {id = 63441, criteria = 115929},
            ZamestoTV_Remix = true,
            note = L["RS_58_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [26343351] = ({
            label = L["Souvenir Seeker 59"],
            cont = true,
            achievement = {id = 63441, criteria = 115930},
            ZamestoTV_Remix = true,
            note = L["RS_59_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [56009500] = ({
            label = L["Souvenir Seeker 60"],
            cont = true,
            achievement = {id = 63441, criteria = 115931},
            ZamestoTV_Remix = true,
            note = L["RS_60_NOTE"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
    },
}